spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      ssl:
        enabled: true
      connect-timeout: 2000ms
      timeout: 3000ms

logging:
  level:
    root: WARN
    com.org: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: authorized
  tracing:
    sampling:
      probability: 0.1

app:
  security:
    injection-guard:
      enabled: true
